"""Notifications package: centralized message templates for the bot."""

from __future__ import annotations

from app.notifications.templates import (
    admin_welcome,
    ask_employee_code,
    ask_task_date,
    ask_task_description,
    ask_task_employee,
    ask_task_priority,
    ask_task_time,
    ask_task_timezone,
    ask_task_title,
    cancelled,
    deadline_passed_admin,
    deadline_passed_employee,
    employee_welcome,
    error_message,
    invalid_input,
    new_task_notification,
    no_tasks,
    not_authorized,
    profile_card,
    registration_failed,
    registration_success,
    reminder_notification,
    settings_menu,
    task_archived,
    task_completed_admin,
    task_completed_employee,
    task_confirm_card,
    task_created_success,
    task_restored,
    welcome_message,
)

__all__ = [
    "admin_welcome",
    "ask_employee_code",
    "ask_task_date",
    "ask_task_description",
    "ask_task_employee",
    "ask_task_priority",
    "ask_task_time",
    "ask_task_timezone",
    "ask_task_title",
    "cancelled",
    "deadline_passed_admin",
    "deadline_passed_employee",
    "employee_welcome",
    "error_message",
    "invalid_input",
    "new_task_notification",
    "no_tasks",
    "not_authorized",
    "profile_card",
    "registration_failed",
    "registration_success",
    "reminder_notification",
    "settings_menu",
    "task_archived",
    "task_completed_admin",
    "task_completed_employee",
    "task_confirm_card",
    "task_created_success",
    "task_restored",
    "welcome_message",
]
